export default {
    skuSearch:{
        url:'api/scm/vopApiAccess/skuSearch'
    },
    querySkuDetail:{
        url:'api/scm/vopApiAccess/querySkuDetail'
    },
    vopOrderApply:{
        url:'api/scm/vopApiAccess/vopOrderApply'
    },
    doPay:{
        url:'api/scm/vopApiAccess/doPay'
    },
    orderCancel:{
        url:'api/scm/vopApiAccess/orderCancel'
    },
    orderTrack:{
        url:'api/scm/vopApiAccess/orderTrack'
    },
    getBalance:{
        url:'api/scm/vopApiAccess/getBalance'
    },
    orderConfirm:{
        url:'api/scm/vopApiAccess/orderConfirm'
    }
}